CREATE TABLE [dbo].[SMEXCEPTIONTB](
	[ID] [nvarchar](32) NOT NULL,
	[EXCEPTIONTYPE] [nvarchar](50) NULL,
	[MESSAGE] [nvarchar](200) NULL,
	[RESULT] [nvarchar](200) NULL,
	[REMARK] [nvarchar](4000) NULL,
	[STATE] [nvarchar](20) NULL,
	[CREATETIME] [datetime] NULL,
 CONSTRAINT [PK_SMEXCEPTIONTB] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SMEXCEPTIONTB] ADD  CONSTRAINT [DF_SMEXCEPTIONTB_STATE]  DEFAULT (N'∆Ù”√') FOR [STATE]
GO

CREATE TABLE [dbo].[SMFIELD](
	[ID] [nvarchar](32) NOT NULL,
	[MYTEXTS] [nvarchar](50) NOT NULL,
	[PARENTID] [nvarchar](32) NULL,
	[MYTABLES] [nvarchar](50) NULL,
	[MYCOLUMS] [nvarchar](50) NULL,
	[SORT] [decimal](6, 0) NULL,
	[REMARK] [nvarchar](200) NULL,
	[CREATETIME] [datetime] NULL,
	[CREATEPERSON] [nvarchar](50) NULL,
	[UPDATETIME] [datetime] NULL,
	[UPDATEPERSON] [nvarchar](50) NULL,
	[MYVALUES] [nvarchar](100) NULL,
 CONSTRAINT [PK_SMFIELD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SMFIELD]  WITH CHECK ADD  CONSTRAINT [FK_SMFIELD_ID] FOREIGN KEY([PARENTID])
REFERENCES [dbo].[SMFIELD] ([ID])
GO

ALTER TABLE [dbo].[SMFIELD] CHECK CONSTRAINT [FK_SMFIELD_ID]
GO

CREATE TABLE [dbo].[SMFUNCTB](
	[FUNC_ID] [int] IDENTITY(1,1) NOT NULL,
	[FUNC_CODE] [nvarchar](32) NULL,
	[FUNC_NAME] [nvarchar](64) NULL,
	[EVENT_NAME] [nvarchar](256) NULL,
	[STATUS] [nvarchar](1) NULL,
	[PARENTFUNC_CODE] [nvarchar](32) NULL,
	[CLASS_NAME] [nvarchar](256) NULL,
	[ORDERCODE] [int] NULL,
	[SM_SYSTEM] [nvarchar](10) NULL,
	[IMGINDEX] [int] NULL,
	[ICONIC] [nvarchar](50) NULL,
 CONSTRAINT [PK_SMFUNCTB] PRIMARY KEY CLUSTERED 
(
	[FUNC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
---------------------------------------------------------------------
CREATE TABLE [dbo].[SMMENUTB](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](200) NULL,
	[PARENTID] [int] NULL,
	[URL] [nvarchar](200) NULL,
	[ICONIC] [nvarchar](200) NULL,
	[SORT] [int] NULL,
	[REMARK] [nvarchar](200) NULL,
	[STATE] [nvarchar](20) NULL,
	[CREATEPERSON] [nvarchar](50) NULL,
	[CREATETIME] [datetime] NULL,
	[UPDATETIME] [datetime] NULL,
	[UPDATEPERSON] [nvarchar](50) NULL,
	[ISLEAF] [nvarchar](20) NULL,
	[MENULEVEL] [int] NULL,
 CONSTRAINT [PK_SMMENUTB] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SMMENUTB]  WITH CHECK ADD  CONSTRAINT [FK_SMMENUTB_ID] FOREIGN KEY([PARENTID])
REFERENCES [dbo].[SMMENUTB] ([ID])
GO

ALTER TABLE [dbo].[SMMENUTB] CHECK CONSTRAINT [FK_SMMENUTB_ID]
GO
CREATE TABLE [dbo].[SMROLETB](
	[ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_NAME] [nvarchar](20) NULL,
	[CREATION_TIME] [datetime] NULL,
	[CREATION_USER] [int] NULL,
	[UPDATE_TIME] [datetime] NULL,
	[UPDATE_USER] [int] NULL,
	[REMARK] [nvarchar](100) NULL,
	[STATUS] [nvarchar](2) NULL,
 CONSTRAINT [PK_SMROLETB] PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[SMUSERTB](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[U_ID] [nvarchar](20) NULL,
	[U_PASSWORD] [nvarchar](50) NULL,
	[GENDER] [nvarchar](1) NULL,
	[USER_NAME] [nvarchar](20) NULL,
	[CREATION_TIME] [datetime] NULL,
	[CREATION_USER] [int] NULL,
	[UPDATE_TIME] [datetime] NULL,
	[UPDATE_USER] [int] NULL,
	[STATUS] [nvarchar](1) NULL,
	[TYPE_ID] [int] NULL,
	[COMPONENT_ID] [int] NULL,
	[COMMUN_ID] [int] NULL,
	[GUILD_CODE] [nvarchar](20) NULL,
	[UNPAYAMT] [int] NULL,
	[CONIFGUSEFUL] [nvarchar](1) NULL,
	[FLAG] [int] NULL,
	[ID_NO] [nvarchar](20) NULL,
	[ISAUDIT] [int] NULL,
	[AUDITPASSWORD] [nvarchar](50) NULL,
 CONSTRAINT [PK_SMUSERTB] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[SMUSERROLETB](
	[USER_ID] [int] NOT NULL,
	[ROLE_ID] [int] NOT NULL,
 CONSTRAINT [PK__SMUSERROLETB__5165187F] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC,
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SMUSERROLETB]  WITH CHECK ADD  CONSTRAINT [FK_SMUSERROLE_ROLE_ID] FOREIGN KEY([ROLE_ID])
REFERENCES [dbo].[SMROLETB] ([ROLE_ID])
GO

ALTER TABLE [dbo].[SMUSERROLETB] CHECK CONSTRAINT [FK_SMUSERROLE_ROLE_ID]
GO

ALTER TABLE [dbo].[SMUSERROLETB]  WITH CHECK ADD  CONSTRAINT [FK_SMUSERROLE_USER_ID] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[SMUSERTB] ([USER_ID])
GO

ALTER TABLE [dbo].[SMUSERROLETB] CHECK CONSTRAINT [FK_SMUSERROLE_USER_ID]
GO
---------------------------------------------------------------------
CREATE TABLE [dbo].[SMMENUFUNCTB](
	[MENUID] [int] NOT NULL,
	[FUNC_ID] [int] NOT NULL,
 CONSTRAINT [PK__SMMENUFUNCTB__5812160E] PRIMARY KEY CLUSTERED 
(
	[MENUID] ASC,
	[FUNC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SMMENUFUNCTB]  WITH CHECK ADD  CONSTRAINT [FK_SMMENUFUNC_FUNCID] FOREIGN KEY([FUNC_ID])
REFERENCES [dbo].[SMFUNCTB] ([FUNC_ID])
GO

ALTER TABLE [dbo].[SMMENUFUNCTB] CHECK CONSTRAINT [FK_SMMENUFUNC_FUNCID]
GO

ALTER TABLE [dbo].[SMMENUFUNCTB]  WITH CHECK ADD  CONSTRAINT [FK_SMMENUFUNC_MENUID] FOREIGN KEY([MENUID])
REFERENCES [dbo].[SMMENUTB] ([ID])
GO

ALTER TABLE [dbo].[SMMENUFUNCTB] CHECK CONSTRAINT [FK_SMMENUFUNC_MENUID]
GO
CREATE TABLE [dbo].[SMMENUROLEFUNCTB](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MENUID] [int] NULL,
	[FUNC_ID] [int] NULL,
	[ROLEID] [int] NULL,
 CONSTRAINT [PK_SMMENUROLEFUNCTB] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SMMENUROLEFUNCTB]  WITH CHECK ADD  CONSTRAINT [FK_SMMENUROLEFUNCTB_SMFUNCTB] FOREIGN KEY([FUNC_ID])
REFERENCES [dbo].[SMFUNCTB] ([FUNC_ID])
GO

ALTER TABLE [dbo].[SMMENUROLEFUNCTB] CHECK CONSTRAINT [FK_SMMENUROLEFUNCTB_SMFUNCTB]
GO

ALTER TABLE [dbo].[SMMENUROLEFUNCTB]  WITH CHECK ADD  CONSTRAINT [FK_SMMENUROLEFUNCTB_SMMENUTB] FOREIGN KEY([MENUID])
REFERENCES [dbo].[SMMENUTB] ([ID])
GO

ALTER TABLE [dbo].[SMMENUROLEFUNCTB] CHECK CONSTRAINT [FK_SMMENUROLEFUNCTB_SMMENUTB]
GO

ALTER TABLE [dbo].[SMMENUROLEFUNCTB]  WITH CHECK ADD  CONSTRAINT [FK_SMMENUROLEFUNCTB_SMROLETB] FOREIGN KEY([ROLEID])
REFERENCES [dbo].[SMROLETB] ([ROLE_ID])
GO

ALTER TABLE [dbo].[SMMENUROLEFUNCTB] CHECK CONSTRAINT [FK_SMMENUROLEFUNCTB_SMROLETB]
GO
CREATE TABLE [dbo].SMLOG(
	[LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[LOG_DATETIME] [datetime] NULL,
	[USER_ID] [int] NULL,
	[FUNC_CODE] [nvarchar](32) NULL,
	[OPERATION_TYPE] [nvarchar](1) NULL,
	[REMARK] [nvarchar](2000) NULL,
	[SYSTEMCODE] [nvarchar](20) NULL,
	[CLASSNAME] [nvarchar](100) NULL,
	[IMPORTANCEDEGREE] [nvarchar](20) NULL,
 CONSTRAINT [PK_OMOPERATIONLOGTB] PRIMARY KEY CLUSTERED 
(
	[LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO