//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RolePermission.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMFIELD
    {
        public SMFIELD()
        {
            this.SMFIELD1 = new HashSet<SMFIELD>();
        }
    
        public int ID { get; set; }
        public string MYTEXTS { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string MYTABLES { get; set; }
        public string MYCOLUMS { get; set; }
        public Nullable<decimal> SORT { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
        public string MYVALUES { get; set; }
    
        public virtual ICollection<SMFIELD> SMFIELD1 { get; set; }
        public virtual SMFIELD SMFIELD2 { get; set; }
    }
}
