//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RolePermission.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMFUNCTB
    {
        public SMFUNCTB()
        {
            this.SMMENUROLEFUNCTB = new HashSet<SMMENUROLEFUNCTB>();
            this.SMMENUTB = new HashSet<SMMENUTB>();
        }
    
        public int FUNC_ID { get; set; }
        public string FUNC_CODE { get; set; }
        public string FUNC_NAME { get; set; }
        public string EVENT_NAME { get; set; }
        public string STATUS { get; set; }
        public string PARENTFUNC_CODE { get; set; }
        public string CLASS_NAME { get; set; }
        public Nullable<int> ORDERCODE { get; set; }
        public string SM_SYSTEM { get; set; }
        public string ICONIC { get; set; }
    
        public virtual ICollection<SMMENUROLEFUNCTB> SMMENUROLEFUNCTB { get; set; }
        public virtual ICollection<SMMENUTB> SMMENUTB { get; set; }
    }
}
