//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RolePermission.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMLOG
    {
        public int LOG_ID { get; set; }
        public Nullable<System.DateTime> LOG_DATETIME { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string FUNC_CODE { get; set; }
        public string OPERATION_TYPE { get; set; }
        public string REMARK { get; set; }
        public string SYSTEMCODE { get; set; }
        public string CLASSNAME { get; set; }
    
        public virtual SMUSERTB SMUSERTB { get; set; }
    }
}
